services:
  tarantool:
    build: ./tarantool
    container_name: vote-tarantool
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool:/opt/tarantool:Z
    environment:
      - TARANTOOL_LOG_LEVEL=5
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=password123

  vote-bot:
    build: ./bot
    container_name: vote-bot
    ports:
      - "8088:8088"
    environment:
      - TARANTOOL_ADDR=tarantool:3301
      - TARANTOOL_USER=admin
      - TARANTOOL_PASSWORD=password123
      - MM_TOKEN=h1kjst8qrbgdudrqxtkyaqcedr
      - MM_SERVER=http://host.docker.internal:8065
      - MM_TEAM=test-org
      - MM_USERNAME=vote-bot
      - PORT=8088
    depends_on:
      tarantool:
        condition: service_healthy
